# Generated by Django 1.10.5 on 2017-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_add_profile")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_medium",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_small",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
