# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0002_increase_max_length")]

    operations = [
        migrations.AddField(
            model_name="profile", name="email_optin", field=models.BooleanField(null=True)
        )
    ]
