# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0004_add_last_active_on")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile", name="toc_optin", field=models.BooleanField(null=True)
        ),
    ]
