# Generated by Django 1.11.10 on 2018-05-15 13:06

from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):

    dependencies = [("profiles", "0005_add_bio_headline_toc")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_file",
            field=models.ImageField(
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_medium_file",
            field=models.ImageField(
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri_medium,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_small_file",
            field=models.ImageField(
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri_small,
            ),
        ),
    ]
