# Generated by Django 2.1.2 on 2018-11-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0008_profile_headline_length")]

    operations = [
        migrations.CreateModel(
            name="UserWebsite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("facebook", "facebook"),
                            ("linkedin", "linkedin"),
                            ("personal", "personal"),
                            ("twitter", "twitter"),
                        ],
                        default="personal",
                        max_length=15,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.Profile",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userwebsite", unique_together={("profile", "site_type")}
        ),
    ]
