# Generated by Django 2.2.13 on 2021-01-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0010_profile_locationjson")]

    operations = [migrations.RemoveField(model_name="profile", name="last_active_on")]
