# Generated by Django 4.1.9 on 2023-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_remove_profile_last_active_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
