extends: stylelint-config-standard-scss
rules:
  selector-class-pattern:
  - ((^Mui[A-Z-])|^([a-z][a-z0-9]*)(-[a-z0-9]+)*$) # kebab-case or Mui class
  - message: "Expected class selector to be kebab-case"