sudo: false
# Set Ruby as the language so it doesn't download the pip things. Instead, let docker do that.
language: ruby

matrix:
  include:
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker-compose -f travis-docker-compose.yml run celery echo
      script: (docker-compose -f travis-docker-compose.yml up celery &); sleep 5; docker-compose -f travis-docker-compose.yml run web tox
      services:
        - docker
      env:
        name: Python
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker build -t travis-watch -f ./travis/Dockerfile-travis-watch .
      script: bash ./travis/js_tests.sh
      services:
        - docker
      env:
        name: JavaScript
