FROM node:10.15.1
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

RUN mkdir /src/

COPY package.json /src/

COPY scripts /src/scripts

RUN node /src/scripts/install_yarn.js

USER node
