version: '3.7'
services:
  web:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: ${DEBUG:-True}
      NODE_ENV: ${NODE_ENV:-development}

  celery:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: ${DEBUG:-True}
      NODE_ENV: ${NODE_ENV:-development}

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src

  watch:
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn


volumes:
  django_media: {}
  yarn-cache: {}
