FROM node:6.2
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

RUN adduser --disabled-password --gecos "" mitodl

COPY package.json /src/

COPY scripts /src/scripts

RUN node /src/scripts/install_yarn.js

RUN mkdir -p /home/mitodl/.cache/yarn

RUN chown mitodl:mitodl /home/mitodl/.cache/yarn

USER mitodl
