version: '3.7'

x-environment:
  &py-environment
  DEBUG: 'False'
  DEV_ENV: 'True'  # necessary to have nginx connect to web container
  NODE_ENV: 'production'
  DATABASE_URL: postgres://postgres@db:5432/postgres
  OPEN_DISCUSSIONS_SECURE_SSL_REDIRECT: 'False'
  OPEN_DISCUSSIONS_DB_DISABLE_SSL: 'True'
  OPEN_DISCUSSIONS_REDDIT_URL: https://reddit.local
  OPEN_DISCUSSIONS_REDDIT_VALIDATE_SSL: 'False'
  OPEN_DISCUSSIONS_REDDIT_CLIENT_ID: od_client_id
  OPEN_DISCUSSIONS_REDDIT_SECRET: od_client_secret
  OPEN_DISCUSSIONS_FEATURES_DEFAULT: 'True'
  OPENSEARCH_URL: elastic:9200
  CELERY_TASK_ALWAYS_EAGER: 'False'
  CELERY_BROKER_URL: redis://redis:6379/4
  CELERY_RESULT_BACKEND: redis://redis:6379/4
  DOCKER_HOST: ${DOCKER_HOST:-missing}
  WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
  TIKA_SERVER_ENDPOINT: ${TIKA_SERVER_ENDPOINT:-http://tika:9998/}
  TIKA_CLIENT_ONLY: 'True'

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-nb
    volumes:
      - .:/src
    environment:
      <<: *py-environment
      BASE_DJANGO_APP_NAME: open_discussions
    env_file: .env
    command: >
      /bin/bash -c '
      sleep 3 &&
      jupyter notebook --no-browser --ip=0.0.0.0 --port=8080'
    ports:
      - "8080:8080"
