# Generated by Django 2.0.8 on 2018-12-21 02:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=128, unique=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.CharField(max_length=1024)),
                ("full_description", models.TextField(null=True)),
                ("level", models.CharField(max_length=128)),
                ("semester", models.CharField(max_length=10)),
                ("language", models.CharField(max_length=128)),
                ("platform", models.CharField(max_length=128)),
                ("year", models.IntegerField()),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("enrollment_start", models.DateTimeField(null=True)),
                ("enrollment_end", models.DateTimeField(null=True)),
                ("image", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("raw_json", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        )
    ]
