# Generated by Django 2.0.8 on 2018-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CoursePrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("mode", models.CharField(max_length=128)),
                ("upgrade_deadline", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="course", name="image"),
        migrations.AddField(
            model_name="course",
            name="image_description",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="course", name="image_src", field=models.URLField(null=True)
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(to="course_catalog.CourseInstructor"),
        ),
        migrations.AddField(
            model_name="course",
            name="prices",
            field=models.ManyToManyField(to="course_catalog.CoursePrice"),
        ),
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.ManyToManyField(to="course_catalog.CourseTopic"),
        ),
    ]
