# Generated by Django 2.0.8 on 2019-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0003_add_related_name_20190108_2355")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.CharField(max_length=1024, null=True),
        )
    ]
