# Generated by Django 2.0.8 on 2019-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0006_adds_timestampedmodel_20190111_0031")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="courseinstructor",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="courseprice",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="coursetopic",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
