# Generated by Django 2.0.8 on 2019-01-14 19:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0009_alter_course_price_digits_20190114_1807")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="enrollment_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="enrollment_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="full_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_src",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="raw_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
