# Generated by Django 2.0.10 on 2019-01-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0010_make_fields_nullable_20190114_1947")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        )
    ]
