# Generated by Django 2.0.10 on 2019-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_catalog",
            "0011_increases_max_length_for_short_description_20190116_1942",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        )
    ]
