# Generated by Django 2.0.10 on 2019-01-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0012_changes_short_description_to_text_field_20190116_2046")
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
