# Generated by Django 2.0.10 on 2019-01-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0013_increases_max_length_for_semester_20190117_1627")
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="featured",
            field=models.BooleanField(default=False),
        )
    ]
