# Generated by Django 2.0.10 on 2019-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0014_course_featured")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image_src",
            field=models.URLField(blank=True, max_length=400, null=True),
        )
    ]
