# Generated by Django 2.0.10 on 2019-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0015_increases_image_src_max_length_20190129_1812")
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="published",
            field=models.BooleanField(default=True),
        )
    ]
