# Generated by Django 2.0.10 on 2019-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0016_adds_course_published_field")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_resource",
            field=models.BooleanField(default=False),
        )
    ]
