# Generated by Django 2.0.10 on 2019-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0017_adds_is_resource_to_course")]

    operations = [
        migrations.RemoveField(model_name="course", name="is_resource"),
        migrations.AddField(
            model_name="course",
            name="learning_resource_type",
            field=models.CharField(default="course", max_length=20),
        ),
    ]
