# Generated by Django 2.1.5 on 2019-03-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0019_course_url")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="availability",
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
