# Generated by Django 2.1.7 on 2019-06-18 16:08

from django.db import migrations, models

from course_catalog.constants import UserListType


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0025_adds_favorites_renames_learningpath")]

    operations = [
        migrations.RenameField(
            model_name="userlistitem", old_name="learning_path", new_name="user_list"
        ),
        migrations.AddField(
            model_name="userlist",
            name="list_type",
            field=models.CharField(default=UserListType.LIST.value, max_length=128),
            preserve_default=False,
        ),
    ]
