# Generated by Django 2.1.7 on 2019-07-11 15:54

from django.db import migrations

from course_catalog.constants import OfferedBy


def depopulate_bootcamps_from_courses(apps, schema_editor):
    """Removes bootcamp records from the Courses table"""
    Course = apps.get_model("course_catalog", "Course")
    Course.objects.filter(offered_by=OfferedBy.bootcamps.value).delete()


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0028_adds_offeredby")]

    operations = [
        migrations.RunPython(
            depopulate_bootcamps_from_courses, reverse_code=migrations.RunPython.noop
        )
    ]
