# Generated by Django 2.1.10 on 2019-07-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0030_related_name_instructors_bootcamp")]

    operations = [
        migrations.CreateModel(
            name="CourseRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("offered_by", models.CharField(blank=True, max_length=128, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("enrollment_start", models.DateTimeField(blank=True, null=True)),
                ("enrollment_end", models.DateTimeField(blank=True, null=True)),
                ("image_src", models.URLField(blank=True, max_length=400, null=True)),
                (
                    "image_description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=128, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("url", models.URLField(max_length=2048, null=True)),
                (
                    "learning_resource_type",
                    models.CharField(default="course", max_length=20),
                ),
                ("course_run_id", models.CharField(max_length=128, unique=True)),
                ("level", models.CharField(blank=True, max_length=128, null=True)),
                ("semester", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_runs",
                        to="course_catalog.Course",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_runs",
                        to="course_catalog.CourseInstructor",
                    ),
                ),
                (
                    "prices",
                    models.ManyToManyField(blank=True, to="course_catalog.CoursePrice"),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="course_catalog.CourseTopic"),
                ),
            ],
            options={"abstract": False},
        )
    ]
