# Generated by Django 2.1.10 on 2019-08-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0031_add_course_run")]

    operations = [
        migrations.AlterField(
            model_name="favoriteitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("course", "bootcamp", "userlist", "program")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="programitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("course", "bootcamp")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="userlistitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("course", "bootcamp")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
