# Generated by Django 2.1.10 on 2019-08-05 15:13

from django.db import migrations, models

import course_catalog.utils


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0032_contenttype_limit_choice_models")]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="image_src",
            field=models.ImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=course_catalog.utils.program_image_upload_uri,
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="image_src",
            field=models.ImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=course_catalog.utils.user_list_image_upload_uri,
            ),
        ),
    ]
