# Generated by Django 2.1.10 on 2019-08-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0033_blankable_image_fields")]

    operations = [
        migrations.AlterModelOptions(
            name="userlist", options={"verbose_name": "user_list"}
        )
    ]
