# Generated by Django 2.1.10 on 2019-08-08 16:55

from django.db import migrations

from search.task_helpers import delete_course, delete_bootcamp


def delete_resources(apps, schema_editor):
    """
    Delete all courses, runs, and bootcamps.  They will need to be imported again.
    """
    Course = apps.get_model("course_catalog", "Course")
    CourseRun = apps.get_model("course_catalog", "CourseRun")
    Bootcamp = apps.get_model("course_catalog", "Bootcamp")

    for course in Course.objects.all():
        course.delete()
        delete_course(course)
    for bootcamp in Bootcamp.objects.all():
        bootcamp.delete()
        delete_bootcamp(bootcamp)
    CourseRun.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("course_catalog", "0033_blankable_image_fields"),
    ]

    operations = [
        migrations.RunPython(delete_resources, reverse_code=migrations.RunPython.noop)
    ]
