# Generated by Django 2.1.10 on 2019-08-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("course_catalog", "0034_delete_resources"),
    ]

    operations = [
        migrations.RemoveField(model_name="bootcamp", name="availability"),
        migrations.RemoveField(model_name="bootcamp", name="end_date"),
        migrations.RemoveField(model_name="bootcamp", name="enrollment_end"),
        migrations.RemoveField(model_name="bootcamp", name="enrollment_start"),
        migrations.RemoveField(model_name="bootcamp", name="instructors"),
        migrations.RemoveField(model_name="bootcamp", name="prices"),
        migrations.RemoveField(model_name="bootcamp", name="start_date"),
        migrations.RemoveField(model_name="bootcamp", name="year"),
        migrations.RemoveField(model_name="bootcamp", name="language"),
        migrations.RemoveField(model_name="course", name="availability"),
        migrations.RemoveField(model_name="course", name="end_date"),
        migrations.RemoveField(model_name="course", name="enrollment_end"),
        migrations.RemoveField(model_name="course", name="enrollment_start"),
        migrations.RemoveField(model_name="course", name="instructors"),
        migrations.RemoveField(model_name="course", name="level"),
        migrations.RemoveField(model_name="course", name="prices"),
        migrations.RemoveField(model_name="course", name="semester"),
        migrations.RemoveField(model_name="course", name="start_date"),
        migrations.RemoveField(model_name="course", name="year"),
        migrations.RemoveField(model_name="course", name="language"),
        migrations.RemoveField(model_name="courserun", name="course"),
        migrations.AddField(
            model_name="courserun",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("course", "bootcamp")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="course_instructors",
                to="course_catalog.CourseInstructor",
            ),
        ),
    ]
