# Generated by Django 2.1.10 on 2019-08-20 21:51

from django.db import migrations, models

from course_catalog.utils import best_run_date


def populate_earliest_dates(apps, schema_editor):
    """
    Delete all courses, runs, and bootcamps.  They will need to be imported again.
    """
    CourseRun = apps.get_model("course_catalog", "CourseRun")

    for course_run in CourseRun.objects.iterator():
        course_run.earliest_start = best_run_date(
            course_run.enrollment_start,
            course_run.start_date,
            course_run.semester,
            course_run.year,
        )
        course_run.earliest_end = best_run_date(
            course_run.enrollment_end,
            course_run.end_date,
            course_run.semester,
            course_run.year,
            ending=True,
        )
        course_run.save()


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0035_courses_to_runs")]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="earliest_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courserun",
            name="earliest_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_earliest_dates, reverse_code=migrations.RunPython.noop
        ),
    ]
