# Generated by Django 2.1.11 on 2019-09-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0036_courserun_earliest_dates")]

    operations = [
        migrations.AddField(
            model_name="program",
            name="program_id",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.RemoveField(model_name="program", name="image_src"),
        migrations.AddField(
            model_name="program",
            name="image_src",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
