# Generated by Django 2.1.11 on 2019-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0037_add_program_fields")]

    operations = [
        migrations.AddField(
            model_name="program",
            name="prices",
            field=models.ManyToManyField(blank=True, to="course_catalog.CoursePrice"),
        )
    ]
