# Generated by Django 2.1.11 on 2019-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0039_add_instructor_fullname")]

    operations = [
        migrations.AddField(
            model_name="program",
            name="published",
            field=models.BooleanField(default=True),
        )
    ]
