# Generated by Django 2.1.11 on 2019-09-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0040_add_program_published")]

    operations = [
        migrations.AlterField(
            model_name="courseprice",
            name="mode",
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
