# Generated by Django 2.1.11 on 2019-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0040_add_program_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='prices',
        ),
        migrations.AlterField(
            model_name='courserun',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('course', 'bootcamp', 'program')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
