# Generated by Django 2.1.11 on 2019-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0044_uniq_by_platform_id")]

    operations = [
        migrations.CreateModel(
            name="LearningResourceOfferor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
            options={"abstract": False},
        ),
        # explicity define db_column to the fields so the rename works and django doesn't expect an add/drop
        migrations.AlterField(
            model_name="bootcamp",
            name="offered_by",
            field=models.CharField(
                blank=True, db_column="offered_by", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="offered_by",
            field=models.CharField(
                blank=True, db_column="offered_by", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="offered_by",
            field=models.CharField(
                blank=True, db_column="offered_by", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="offered_by",
            field=models.CharField(
                blank=True, db_column="offered_by", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="offered_by",
            field=models.CharField(
                blank=True, db_column="offered_by", max_length=128, null=True
            ),
        ),
        # rename the fields
        migrations.RenameField(
            model_name="bootcamp",
            old_name="offered_by",
            new_name="_deprecated_offered_by",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="offered_by",
            new_name="_deprecated_offered_by",
        ),
        migrations.RenameField(
            model_name="learningresourcerun",
            old_name="offered_by",
            new_name="_deprecated_offered_by",
        ),
        migrations.RenameField(
            model_name="program",
            old_name="offered_by",
            new_name="_deprecated_offered_by",
        ),
        migrations.RenameField(
            model_name="userlist",
            old_name="offered_by",
            new_name="_deprecated_offered_by",
        ),
    ]
