# Generated by Django 2.1.11 on 2019-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0047_add_video_resource")]

    operations = [
        migrations.AlterField(
            model_name="userlist",
            name="privacy_level",
            field=models.CharField(default="private", max_length=32),
        )
    ]
