# Generated by Django 2.1.11 on 2019-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0048_privacy_default")]

    operations = [migrations.RenameModel(old_name="VideoResource", new_name="Video")]
