# Generated by Django 2.1.11 on 2019-10-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0049_rename_video_resource_to_video")]

    operations = [
        migrations.AlterModelOptions(
            name="userlist", options={"verbose_name": "userlist"}
        )
    ]
