# Generated by Django 2.1.11 on 2019-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0050_userlist_verbosename")]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        )
    ]
