# Generated by Django 2.1.11 on 2019-11-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0051_add_video_duration")]

    operations = [
        migrations.AlterField(
            model_name="favoriteitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("course", "bootcamp", "userlist", "program", "video")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="userlistitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("course", "bootcamp", "program", "video", "userlist")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
