# Generated by Django 2.1.11 on 2019-11-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0052_userlistitem_contenttypes")]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "_deprecated_offered_by",
                    models.CharField(
                        blank=True, db_column="offered_by", max_length=128, null=True
                    ),
                ),
                (
                    "image_description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("platform", models.CharField(max_length=40)),
                ("playlist_id", models.CharField(max_length=80)),
                ("image_src", models.URLField(blank=True, max_length=400, null=True)),
                ("url", models.URLField(max_length=2048, null=True)),
                ("published", models.BooleanField(default=True)),
                ("has_user_list", models.BooleanField(default=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="course_catalog.Playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="course_catalog.Video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "_deprecated_offered_by",
                    models.CharField(
                        blank=True, db_column="offered_by", max_length=128, null=True
                    ),
                ),
                ("platform", models.CharField(max_length=40)),
                ("channel_id", models.CharField(max_length=80)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("published", models.BooleanField(default=True)),
                (
                    "offered_by",
                    models.ManyToManyField(
                        blank=True, to="course_catalog.LearningResourceOfferor"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="course_catalog.CourseTopic"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="playlist",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="course_catalog.VideoChannel",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="offered_by",
            field=models.ManyToManyField(
                blank=True, to="course_catalog.LearningResourceOfferor"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="topics",
            field=models.ManyToManyField(blank=True, to="course_catalog.CourseTopic"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                through="course_catalog.PlaylistVideo", to="course_catalog.Video"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistvideo", unique_together={("playlist", "video")}
        ),
    ]
