# Generated by Django 2.1.11 on 2019-11-18 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0053_add_channel_playlist_models")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="user_list",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist",
                to="course_catalog.UserList",
            ),
        )
    ]
