# Generated by Django 2.1.11 on 2019-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0055_add_video_runs")]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="image_src",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_src",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="image_src",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
