# Generated by Django 2.1.11 on 2019-12-05 19:23

import django.db.models.deletion
from django.db import migrations, models


def remove_userlist_listitems(apps, schema_editor):
    """Delete any existing user list items in user lists
    """
    UserListItem = apps.get_model("course_catalog", "UserListItem")
    UserListItem.objects.filter(content_type__model="userlist").delete()


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0056_course_image_src_widen")]

    operations = [
        migrations.RunPython(
            remove_userlist_listitems, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="userlistitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("course", "bootcamp", "program", "video")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
