# Generated by Django 2.1.11 on 2019-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0057_no_userlist_listitems")]

    operations = [
        migrations.AlterField(
            model_name="learningresourceofferor",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        )
    ]
