# Generated by Django 2.1.11 on 2019-12-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0058_increase_learningresourceofferor_name_length")
    ]

    operations = [
        migrations.RemoveField(model_name="bootcamp", name="_deprecated_offered_by"),
        migrations.RemoveField(model_name="course", name="_deprecated_offered_by"),
        migrations.RemoveField(
            model_name="learningresourcerun", name="_deprecated_offered_by"
        ),
        migrations.RemoveField(model_name="playlist", name="_deprecated_offered_by"),
        migrations.RemoveField(model_name="program", name="_deprecated_offered_by"),
        migrations.RemoveField(model_name="userlist", name="_deprecated_offered_by"),
        migrations.RemoveField(model_name="video", name="_deprecated_offered_by"),
        migrations.RemoveField(
            model_name="videochannel", name="_deprecated_offered_by"
        ),
    ]
