# Generated by Django 2.2.9 on 2020-02-13 14:43

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0059_remove_deprecated_offered_by")]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="raw_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="raw_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("uid", models.CharField(blank=True, max_length=36, null=True)),
                ("key", models.CharField(blank=True, max_length=1024, null=True)),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("short_url", models.TextField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=128, null=True)),
                ("section", models.CharField(blank=True, max_length=512, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "content_title",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "content_author",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "content_language",
                    models.CharField(blank=True, max_length=24, null=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("page", "page"), ("file", "file")],
                        default="file",
                        max_length=10,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_files",
                        to="course_catalog.LearningResourceRun",
                    ),
                ),
            ],
            options={
                "verbose_name": "contentfile",
                "unique_together": {("key", "run")},
            },
        ),
    ]
