# Generated by Django 2.2.9 on 2020-02-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0060_move_rawjson_add_contentfile")]

    operations = [
        migrations.AlterField(
            model_name="contentfile",
            name="uid",
            field=models.CharField(blank=True, max_length=36, null=True),
        )
    ]
