# Generated by Django 2.2.10 on 2020-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0060_contentfile_moverawjson")]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="image_src",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_src",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="image_src",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
