# Generated by Django 2.2.10 on 2020-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0061_image_src_maxlength")]

    operations = [
        migrations.AlterField(
            model_name="contentfile",
            name="content_type",
            field=models.CharField(
                choices=[("page", "page"), ("file", "file"), ("vertical", "vertical")],
                default="file",
                max_length=10,
            ),
        )
    ]
