# Generated by Django 2.2.9 on 2020-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0061_contentfile_nullable_uid")]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="content_author",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="content_language",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="content_title",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="section",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
