# Generated by Django 2.2.10 on 2020-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("course_catalog", "0063_intructor_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerun",
            name="platform",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="course", unique_together={("platform", "course_id")}
        ),
        migrations.AlterUniqueTogether(
            name="learningresourcerun", unique_together={("platform", "run_id")}
        ),
        migrations.AlterIndexTogether(
            name="bootcamp", index_together={("id", "published")}
        ),
        migrations.AlterIndexTogether(
            name="learningresourcerun",
            index_together={
                ("content_type", "object_id"),
                ("content_type", "start_date"),
            },
        ),
    ]
