# Generated by Django 2.2.10 on 2020-04-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0065_higher_prices")]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("podcast_id", models.CharField(max_length=80, unique=True)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("image_src", models.URLField(blank=True, max_length=400, null=True)),
                ("published", models.BooleanField(default=True)),
                ("url", models.URLField(max_length=2048, null=True)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "offered_by",
                    models.ManyToManyField(
                        blank=True, to="course_catalog.LearningResourceOfferor"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="course_catalog.CourseTopic"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="favoriteitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": (
                        "course",
                        "bootcamp",
                        "userlist",
                        "program",
                        "video",
                        "podcast",
                        "podcastepisode",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="userlistitem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": (
                        "course",
                        "bootcamp",
                        "program",
                        "video",
                        "podcast",
                        "podcastepisode",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("episode_id", models.CharField(max_length=80)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("image_src", models.URLField(blank=True, max_length=400, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("published", models.BooleanField(default=True)),
                ("transcript", models.TextField(blank=True, default="")),
                ("url", models.URLField(max_length=2048, null=True)),
                ("searchable", models.BooleanField(default=True)),
                ("duration", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "offered_by",
                    models.ManyToManyField(
                        blank=True, to="course_catalog.LearningResourceOfferor"
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="course_catalog.Podcast",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="course_catalog.CourseTopic"),
                ),
            ],
            options={"unique_together": {("podcast", "episode_id")}},
        ),
    ]
