# Generated by Django 2.2.10 on 2020-04-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0066_podcast_podcastepisode")]

    operations = [
        migrations.AlterModelOptions(name="podcast", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(
            name="podcastepisode", options={"ordering": ("id",)}
        ),
    ]
