# Generated by Django 2.2.10 on 2020-04-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0067_podcast_ordering")]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerun",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": (
                        "course",
                        "bootcamp",
                        "program",
                        "video",
                        "podcast",
                        "podcastepisode",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        )
    ]
