# Generated by Django 2.2.10 on 2020-04-17 19:00

from django.db import migrations

from course_catalog.constants import PlatformType


def delete_related_bootcamps(apps, schema_editor):
    """Populate all platform fields"""
    ContentType = apps.get_model("contenttypes", "ContentType")
    LearningResourceRun = apps.get_model("course_catalog", "LearningResourceRun")
    LearningResourceRun.objects.filter(platform=PlatformType.bootcamps.value).delete()
    ContentType.objects.filter(model="bootcamp").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0068_add_podcast_podcastepisode_to_learningresourserun")
    ]

    operations = [
        migrations.RunPython(
            delete_related_bootcamps, reverse_code=migrations.RunPython.noop
        )
    ]
