# Generated by Django 2.2.10 on 2020-04-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0070_delete_bootcamp")]

    operations = [
        migrations.AlterModelOptions(
            name="podcastepisode",
            options={"ordering": ("id",), "verbose_name": "podcastepisode"},
        )
    ]
