# Generated by Django 2.2.13 on 2020-06-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0072_podcastepisode_episode_link")]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerun",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("course", "bootcamp", "program")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        )
    ]
