# Generated by Django 2.2.10 on 2020-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0073_remove_runs_for_videos_and_podcasts")]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="apple_podcasts_url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="google_podcasts_url",
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
