# Generated by Django 2.2.13 on 2020-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0074_add_podcast_subscribe_urls")]

    operations = [
        migrations.AddField(
            model_name="podcastepisode",
            name="rss",
            field=models.TextField(blank=True, null=True),
        )
    ]
