# Generated by Django 2.2.13 on 2020-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0075_podcastepisode_rss")]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="rss_url",
            field=models.URLField(max_length=2048, null=True),
        )
    ]
