# Generated by Django 2.2.13 on 2020-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0078_course_department")]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="section_slug",
            field=models.CharField(blank=True, max_length=512, null=True),
        )
    ]
