# Generated by Django 2.2.13 on 2021-02-28 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_catalog", "0081_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="course_catalog.Course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrollments_table_run_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="course_catalog.LearningResourceRun",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment", unique_together={("user", "enrollments_table_run_id")}
        ),
    ]
