# Generated by Django 2.2.13 on 2021-03-01 18:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0081_enrollment")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_feature_tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
