# Generated by Django 2.2.13 on 2021-03-01 18:34

import django.contrib.postgres.fields.jsonb
from django.core.paginator import Paginator
from django.db import migrations

from course_catalog.constants import PlatformType


def chunked_iterator(queryset):
    paginator = Paginator(queryset, 100)
    for page in range(1, paginator.num_pages + 1):
        for obj in paginator.page(page).object_list:
            yield obj


def set_feature_tags(apps, schema_editor):
    """Save feature tags for every OCW course based on the run's raw_json
    """
    Course = apps.get_model("course_catalog", "Course")
    LearningResourceRun = apps.get_model("course_catalog", "LearningResourceRun")
    for run in chunked_iterator(
        LearningResourceRun.objects.filter(platform=PlatformType.ocw.value)
        .all()
        .order_by("id")
    ):
        course = Course.objects.get(id=run.object_id)
        if run and run.raw_json:
            course.course_feature_tags = [
                tag["course_feature_tag"]
                for tag in run.raw_json.get("course_feature_tags", [])
            ]
            course.save()


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0082_enrollment_updates")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_feature_tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(set_feature_tags, reverse_code=migrations.RunPython.noop),
    ]
