# Generated by Django 2.2.20 on 2021-06-02 02:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("course_catalog", "0083_course_feature_tags")]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
                ALTER TABLE "course_catalog_course"
                ALTER COLUMN "department" TYPE varchar(256)[] 
                USING CASE WHEN "department" IS NULL THEN NULL
                ELSE array["department"]
                END;
            """
                )
            ],
            reverse_sql=[
                (
                    """
                ALTER TABLE "course_catalog_course" 
                ALTER COLUMN "department" TYPE varchar(256) 
                USING CASE WHEN "department" IS NULL THEN NULL
                WHEN array_length("department",1)=0 THEN NULL
                ELSE "department"[1]
                END
                ;
            """
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="course",
                    name="department",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                )
            ],
        )
    ]
