# Generated by Django 2.2.24 on 2022-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0086_fix_undersized_video_duration")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ocw_next_course",
            field=models.BooleanField(default=False),
        )
    ]
