# Generated by Django 2.2.24 on 2022-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0087_course_ocw_next_course")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image_src",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="image_src",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
