# Generated by Django 2.2.24 on 2022-01-27 22:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0088_change_image_src_type")]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="learning_resource_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=256),
                blank=True,
                null=True,
                size=None,
            ),
        )
    ]
