# Generated by Django 2.2.27 on 2022-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0092_remove_instructor_dupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
