# Generated by Django 3.1 on 2021-01-28 16:27
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations

from course_catalog import constants


def add_staff_list_group(apps, schema_editor):
    """
    Create the staff list editors group
    """
    Group.objects.get_or_create(name=constants.GROUP_STAFF_LISTS_EDITORS)


def remove_staff_list_group(apps, schema_editor):
    """
    Delete the staff list editors group
    """
    Group.objects.filter(name=constants.GROUP_STAFF_LISTS_EDITORS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0093_instructor_fullname_unique"),
    ]

    operations = [
        migrations.RunPython(add_staff_list_group, remove_staff_list_group),
    ]
