# Generated by Django 2.2.28 on 2023-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0095_staff_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
