# Generated by Django 4.1.9 on 2023-07-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_catalog", "0097_alter_course_course_feature_tags_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
