# Generated by Django 2.2.9 on 2020-02-05 16:56

import django.db.models.deletion
from django.db import migrations, models

import open_discussions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [("contenttypes", "0002_remove_content_type_name")]

    operations = [
        migrations.CreateModel(
            name="ContentTypeInteraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_type", models.CharField(max_length=30)),
                ("content_id", models.PositiveIntegerField()),
                (
                    "recorded_on",
                    models.DateTimeField(default=open_discussions.utils.now_in_utc),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        )
    ]
