// flow-typed signature: 61172545648e0b827345db236f81d0ae
// flow-typed version: <<STUB>>/babel-plugin-jsx_v^1.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-jsx/gen' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/lib/babel-jsx' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/lib/helpers' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/lib/meta' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/man/test-out' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/man/test' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/man/test' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/missing_scope' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/children/_header' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/children/custom_first' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/children/js_values' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/children/member_first' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/children/namespaced_first' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/_header' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/basic' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/namespaced' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/spread_alone' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/spread_first' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/props/spread' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/tags/_header' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/tags/basic' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/tags/member_expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx/tests/syntax/tags/namespaced' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-jsx/gen.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/gen'>;
}
declare module 'babel-plugin-jsx/index' {
  declare module.exports: $Exports<'babel-plugin-jsx'>;
}
declare module 'babel-plugin-jsx/index.js' {
  declare module.exports: $Exports<'babel-plugin-jsx'>;
}
declare module 'babel-plugin-jsx/lib/babel-jsx.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/lib/babel-jsx'>;
}
declare module 'babel-plugin-jsx/lib/helpers.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/lib/helpers'>;
}
declare module 'babel-plugin-jsx/lib/meta.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/lib/meta'>;
}
declare module 'babel-plugin-jsx/tests/man/test-out.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/man/test-out'>;
}
declare module 'babel-plugin-jsx/tests/man/test.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/man/test'>;
}
declare module 'babel-plugin-jsx/tests/man/test.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/man/test'>;
}
declare module 'babel-plugin-jsx/tests/missing_scope.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/missing_scope'>;
}
declare module 'babel-plugin-jsx/tests/syntax.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax'>;
}
declare module 'babel-plugin-jsx/tests/syntax/children/_header.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/children/_header'>;
}
declare module 'babel-plugin-jsx/tests/syntax/children/custom_first.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/children/custom_first'>;
}
declare module 'babel-plugin-jsx/tests/syntax/children/js_values.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/children/js_values'>;
}
declare module 'babel-plugin-jsx/tests/syntax/children/member_first.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/children/member_first'>;
}
declare module 'babel-plugin-jsx/tests/syntax/children/namespaced_first.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/children/namespaced_first'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/_header.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/_header'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/basic.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/basic'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/namespaced.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/namespaced'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/spread_alone.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/spread_alone'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/spread_first.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/spread_first'>;
}
declare module 'babel-plugin-jsx/tests/syntax/props/spread.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/props/spread'>;
}
declare module 'babel-plugin-jsx/tests/syntax/tags/_header.js' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/tags/_header'>;
}
declare module 'babel-plugin-jsx/tests/syntax/tags/basic.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/tags/basic'>;
}
declare module 'babel-plugin-jsx/tests/syntax/tags/member_expression.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/tags/member_expression'>;
}
declare module 'babel-plugin-jsx/tests/syntax/tags/namespaced.jsx' {
  declare module.exports: $Exports<'babel-plugin-jsx/tests/syntax/tags/namespaced'>;
}
