// flow-typed signature: 998035132854d70bfb69aba2fb4c2fbf
// flow-typed version: <<STUB>>/eslint-config-mitodl_v0.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mitodl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mitodl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-mitodl/index' {
  declare module.exports: $Exports<'eslint-config-mitodl'>;
}
declare module 'eslint-config-mitodl/index.js' {
  declare module.exports: $Exports<'eslint-config-mitodl'>;
}
