// flow-typed signature: 84eef130e971f974808bf17a8c117349
// flow-typed version: <<STUB>>/redux-hammock_v^0.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-hammock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-hammock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-hammock/constants' {
  declare module.exports: any;
}

declare module 'redux-hammock/django_csrf_fetch' {
  declare module.exports: any;
}

declare module 'redux-hammock/hammock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-hammock/constants.js' {
  declare module.exports: $Exports<'redux-hammock/constants'>;
}
declare module 'redux-hammock/django_csrf_fetch.js' {
  declare module.exports: $Exports<'redux-hammock/django_csrf_fetch'>;
}
declare module 'redux-hammock/hammock.js' {
  declare module.exports: $Exports<'redux-hammock/hammock'>;
}
