// flow-typed signature: be02f448dd536ca81a80fdf8bd4e48ed
// flow-typed version: <<STUB>>/redux-asserts_v^0.0.10/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-asserts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-asserts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-asserts/lib/index' {
  declare module.exports: any;
}

declare module 'redux-asserts/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-asserts/lib/index.js' {
  declare module.exports: $Exports<'redux-asserts/lib/index'>;
}
declare module 'redux-asserts/src/index.js' {
  declare module.exports: $Exports<'redux-asserts/src/index'>;
}
