// flow-typed signature: 211496676eaca44eacfe30c4ce50a400
// flow-typed version: <<STUB>>/redux-debounced_v^0.5.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-debounced'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-debounced' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-debounced/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-debounced/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-debounced/lib/index' {
  declare module.exports: any;
}

declare module 'redux-debounced/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-debounced/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-debounced/coverage/lcov-report/prettify'>;
}
declare module 'redux-debounced/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-debounced/coverage/lcov-report/sorter'>;
}
declare module 'redux-debounced/lib/index.js' {
  declare module.exports: $Exports<'redux-debounced/lib/index'>;
}
declare module 'redux-debounced/test/index.js' {
  declare module.exports: $Exports<'redux-debounced/test/index'>;
}
