// flow-typed signature: db294320ec2621e1dcd7c4087af56dc7
// flow-typed version: <<STUB>>/spinkit_v^1.2.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spinkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spinkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spinkit/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spinkit/gulpfile.js' {
  declare module.exports: $Exports<'spinkit/gulpfile'>;
}
