// flow-typed signature: b0f5f9c76216a09edbaec89bb6eef04a
// flow-typed version: <<STUB>>/@mitodl/mdl-react-components_v^0.0.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mitodl/mdl-react-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mitodl/mdl-react-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mitodl/mdl-react-components/lib/Button' {
  declare module.exports: any;
}

declare module '@mitodl/mdl-react-components/lib/Dialog' {
  declare module.exports: any;
}

declare module '@mitodl/mdl-react-components/lib/index' {
  declare module.exports: any;
}

declare module '@mitodl/mdl-react-components/lib/Radio' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mitodl/mdl-react-components/lib/Button.js' {
  declare module.exports: $Exports<'@mitodl/mdl-react-components/lib/Button'>;
}
declare module '@mitodl/mdl-react-components/lib/Dialog.js' {
  declare module.exports: $Exports<'@mitodl/mdl-react-components/lib/Dialog'>;
}
declare module '@mitodl/mdl-react-components/lib/index.js' {
  declare module.exports: $Exports<'@mitodl/mdl-react-components/lib/index'>;
}
declare module '@mitodl/mdl-react-components/lib/Radio.js' {
  declare module.exports: $Exports<'@mitodl/mdl-react-components/lib/Radio'>;
}
