# Generated by Django 4.2.15 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keycloak_user_export", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexporttokeycloak",
            name="action",
            field=models.CharField(default="ADDED", max_length=20),
        ),
    ]
