// flow-typed signature: 62624ae069e2d3465867ccf4f3b2d7b2
// flow-typed version: <<STUB>>/@material/base_v^0.2.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/base/component' {
  declare module.exports: any;
}

declare module '@material/base/dist/mdc.base' {
  declare module.exports: any;
}

declare module '@material/base/dist/mdc.base.min' {
  declare module.exports: any;
}

declare module '@material/base/foundation' {
  declare module.exports: any;
}

declare module '@material/base/selection-control' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/base/component.js' {
  declare module.exports: $Exports<'@material/base/component'>;
}
declare module '@material/base/dist/mdc.base.js' {
  declare module.exports: $Exports<'@material/base/dist/mdc.base'>;
}
declare module '@material/base/dist/mdc.base.min.js' {
  declare module.exports: $Exports<'@material/base/dist/mdc.base.min'>;
}
declare module '@material/base/foundation.js' {
  declare module.exports: $Exports<'@material/base/foundation'>;
}
declare module '@material/base/index' {
  declare module.exports: $Exports<'@material/base'>;
}
declare module '@material/base/index.js' {
  declare module.exports: $Exports<'@material/base'>;
}
declare module '@material/base/selection-control.js' {
  declare module.exports: $Exports<'@material/base/selection-control'>;
}
