// flow-typed signature: ce0a80f82ccf8dfbb7828d015a694632
// flow-typed version: <<STUB>>/@material/button_v^0.3.11/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
