// flow-typed signature: 4871cd32c0c2e90551835958df15068c
// flow-typed version: <<STUB>>/@material/dialog_v^0.27.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/dialog/constants' {
  declare module.exports: any;
}

declare module '@material/dialog/dist/mdc.dialog' {
  declare module.exports: any;
}

declare module '@material/dialog/dist/mdc.dialog.min' {
  declare module.exports: any;
}

declare module '@material/dialog/foundation' {
  declare module.exports: any;
}

declare module '@material/dialog/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/dialog/constants.js' {
  declare module.exports: $Exports<'@material/dialog/constants'>;
}
declare module '@material/dialog/dist/mdc.dialog.js' {
  declare module.exports: $Exports<'@material/dialog/dist/mdc.dialog'>;
}
declare module '@material/dialog/dist/mdc.dialog.min.js' {
  declare module.exports: $Exports<'@material/dialog/dist/mdc.dialog.min'>;
}
declare module '@material/dialog/foundation.js' {
  declare module.exports: $Exports<'@material/dialog/foundation'>;
}
declare module '@material/dialog/index' {
  declare module.exports: $Exports<'@material/dialog'>;
}
declare module '@material/dialog/index.js' {
  declare module.exports: $Exports<'@material/dialog'>;
}
declare module '@material/dialog/util.js' {
  declare module.exports: $Exports<'@material/dialog/util'>;
}
