// flow-typed signature: b1c06be20e244748adf091a9502c38e3
// flow-typed version: <<STUB>>/@material/drawer_v^0.5.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/drawer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/drawer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/drawer/dist/mdc.drawer' {
  declare module.exports: any;
}

declare module '@material/drawer/dist/mdc.drawer.min' {
  declare module.exports: any;
}

declare module '@material/drawer/persistent/constants' {
  declare module.exports: any;
}

declare module '@material/drawer/persistent/foundation' {
  declare module.exports: any;
}

declare module '@material/drawer/persistent/index' {
  declare module.exports: any;
}

declare module '@material/drawer/slidable/constants' {
  declare module.exports: any;
}

declare module '@material/drawer/slidable/foundation' {
  declare module.exports: any;
}

declare module '@material/drawer/slidable/index' {
  declare module.exports: any;
}

declare module '@material/drawer/temporary/constants' {
  declare module.exports: any;
}

declare module '@material/drawer/temporary/foundation' {
  declare module.exports: any;
}

declare module '@material/drawer/temporary/index' {
  declare module.exports: any;
}

declare module '@material/drawer/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/drawer/dist/mdc.drawer.js' {
  declare module.exports: $Exports<'@material/drawer/dist/mdc.drawer'>;
}
declare module '@material/drawer/dist/mdc.drawer.min.js' {
  declare module.exports: $Exports<'@material/drawer/dist/mdc.drawer.min'>;
}
declare module '@material/drawer/index' {
  declare module.exports: $Exports<'@material/drawer'>;
}
declare module '@material/drawer/index.js' {
  declare module.exports: $Exports<'@material/drawer'>;
}
declare module '@material/drawer/persistent/constants.js' {
  declare module.exports: $Exports<'@material/drawer/persistent/constants'>;
}
declare module '@material/drawer/persistent/foundation.js' {
  declare module.exports: $Exports<'@material/drawer/persistent/foundation'>;
}
declare module '@material/drawer/persistent/index.js' {
  declare module.exports: $Exports<'@material/drawer/persistent/index'>;
}
declare module '@material/drawer/slidable/constants.js' {
  declare module.exports: $Exports<'@material/drawer/slidable/constants'>;
}
declare module '@material/drawer/slidable/foundation.js' {
  declare module.exports: $Exports<'@material/drawer/slidable/foundation'>;
}
declare module '@material/drawer/slidable/index.js' {
  declare module.exports: $Exports<'@material/drawer/slidable/index'>;
}
declare module '@material/drawer/temporary/constants.js' {
  declare module.exports: $Exports<'@material/drawer/temporary/constants'>;
}
declare module '@material/drawer/temporary/foundation.js' {
  declare module.exports: $Exports<'@material/drawer/temporary/foundation'>;
}
declare module '@material/drawer/temporary/index.js' {
  declare module.exports: $Exports<'@material/drawer/temporary/index'>;
}
declare module '@material/drawer/util.js' {
  declare module.exports: $Exports<'@material/drawer/util'>;
}
