// flow-typed signature: f0f7757064f9b57f368de815c1ec114e
// flow-typed version: <<STUB>>/@material/list_v^0.2.14/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/list' {
  declare module.exports: any;
}
