// flow-typed signature: 142ef1ef152dfbe4c07271a04653928e
// flow-typed version: <<STUB>>/@material/menu_v^0.4.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/menu/dist/mdc.menu' {
  declare module.exports: any;
}

declare module '@material/menu/dist/mdc.menu.min' {
  declare module.exports: any;
}

declare module '@material/menu/simple/adapter' {
  declare module.exports: any;
}

declare module '@material/menu/simple/constants' {
  declare module.exports: any;
}

declare module '@material/menu/simple/foundation' {
  declare module.exports: any;
}

declare module '@material/menu/simple/index' {
  declare module.exports: any;
}

declare module '@material/menu/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/menu/dist/mdc.menu.js' {
  declare module.exports: $Exports<'@material/menu/dist/mdc.menu'>;
}
declare module '@material/menu/dist/mdc.menu.min.js' {
  declare module.exports: $Exports<'@material/menu/dist/mdc.menu.min'>;
}
declare module '@material/menu/index' {
  declare module.exports: $Exports<'@material/menu'>;
}
declare module '@material/menu/index.js' {
  declare module.exports: $Exports<'@material/menu'>;
}
declare module '@material/menu/simple/adapter.js' {
  declare module.exports: $Exports<'@material/menu/simple/adapter'>;
}
declare module '@material/menu/simple/constants.js' {
  declare module.exports: $Exports<'@material/menu/simple/constants'>;
}
declare module '@material/menu/simple/foundation.js' {
  declare module.exports: $Exports<'@material/menu/simple/foundation'>;
}
declare module '@material/menu/simple/index.js' {
  declare module.exports: $Exports<'@material/menu/simple/index'>;
}
declare module '@material/menu/util.js' {
  declare module.exports: $Exports<'@material/menu/util'>;
}
