// flow-typed signature: e2cc29a99edb44ce6a90e664b5167810
// flow-typed version: <<STUB>>/@material/rtl_v^0.1.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/rtl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/rtl' {
  declare module.exports: any;
}
