// flow-typed signature: f0fdabfbf701116c9aa3c6bbba8a8d6c
// flow-typed version: <<STUB>>/@material/toolbar_v^0.4.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/toolbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/toolbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/toolbar/constants' {
  declare module.exports: any;
}

declare module '@material/toolbar/dist/mdc.toolbar' {
  declare module.exports: any;
}

declare module '@material/toolbar/dist/mdc.toolbar.min' {
  declare module.exports: any;
}

declare module '@material/toolbar/foundation' {
  declare module.exports: any;
}

declare module '@material/toolbar/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/toolbar/constants.js' {
  declare module.exports: $Exports<'@material/toolbar/constants'>;
}
declare module '@material/toolbar/dist/mdc.toolbar.js' {
  declare module.exports: $Exports<'@material/toolbar/dist/mdc.toolbar'>;
}
declare module '@material/toolbar/dist/mdc.toolbar.min.js' {
  declare module.exports: $Exports<'@material/toolbar/dist/mdc.toolbar.min'>;
}
declare module '@material/toolbar/foundation.js' {
  declare module.exports: $Exports<'@material/toolbar/foundation'>;
}
declare module '@material/toolbar/index' {
  declare module.exports: $Exports<'@material/toolbar'>;
}
declare module '@material/toolbar/index.js' {
  declare module.exports: $Exports<'@material/toolbar'>;
}
declare module '@material/toolbar/util.js' {
  declare module.exports: $Exports<'@material/toolbar/util'>;
}
