# Generated by Django 2.2.27 on 2022-06-14 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("widgets", "0002_remove_text"),
        ("auth", "0011_update_proxy_permissions"),
        ("course_catalog", "0090_contentfile_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        max_length=2083, null=True, upload_to=profiles.utils.avatar_uri
                    ),
                ),
                (
                    "avatar_small",
                    models.ImageField(
                        blank=True,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.avatar_uri_small,
                    ),
                ),
                (
                    "avatar_medium",
                    models.ImageField(
                        blank=True,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.avatar_uri_medium,
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.banner_uri,
                    ),
                ),
                (
                    "ga_tracking_id",
                    models.CharField(blank=True, max_length=24, null=True),
                ),
                (
                    "about",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "featured_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course_catalog.UserList",
                    ),
                ),
                (
                    "widget_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="widgets.WidgetList",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="FieldChannelGroupRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("moderators", "moderators")], max_length=48
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels_fields.FieldChannel",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.Group"
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "group", "role")},
                "index_together": {("field", "role")},
            },
        ),
    ]
