# Generated by Django 2.2.27 on 2022-07-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("channels_fields", "0002_field_channel_lists")]

    operations = [
        migrations.CreateModel(
            name="Subfield",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "field_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels_fields.FieldChannel",
                    ),
                ),
                (
                    "parent_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfields",
                        to="channels_fields.FieldChannel",
                    ),
                ),
            ],
            options={"unique_together": {("field_channel", "parent_channel")}},
        )
    ]
