# Generated by Django 2.2.27 on 2022-07-21 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ("channels_fields", "0003_subfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldchannel",
            name="avatar_medium",
        ),
        migrations.RemoveField(
            model_name="fieldchannel",
            name="avatar_small",
        ),
        migrations.RemoveField(
            model_name="fieldchannel",
            name="description",
        ),
        migrations.AddField(
            model_name="fieldchannel",
            name="public_description",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                max_length=2083, null=True, upload_to=profiles.utils.avatar_uri
            ),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                max_length=2083, null=True, upload_to=profiles.utils.banner_uri
            ),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Channel name can only contain the characters: A-Z, a-z, 0-9, _",
                        regex="^[A-Za-z0-9_]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="widget_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_channel",
                to="widgets.WidgetList",
            ),
        ),
    ]
