# Generated by Django 2.2.27 on 2022-07-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels_fields", "0004_field_channel_refactor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldlist",
            options={"ordering": ["position"]},
        ),
    ]
