# Generated by Django 2.2.27 on 2022-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels_fields", "0005_field_lists_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="public_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
