# Generated by Django 4.1.9 on 2023-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels_fields", "0007_blankable_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="about",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
