# Generated by Django 2.2.27 on 2022-06-10 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0002_remove_text'),
        ('course_catalog', '0090_contentfile_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('membership_is_managed', models.BooleanField(default=False)),
                ('avatar', models.ImageField(max_length=2083, null=True, upload_to=profiles.utils.avatar_uri)),
                ('avatar_small', models.ImageField(blank=True, max_length=2083, null=True, upload_to=profiles.utils.avatar_uri_small)),
                ('avatar_medium', models.ImageField(blank=True, max_length=2083, null=True, upload_to=profiles.utils.avatar_uri_medium)),
                ('banner', models.ImageField(blank=True, max_length=2083, null=True, upload_to=profiles.utils.banner_uri)),
                ('ga_tracking_id', models.CharField(blank=True, max_length=24, null=True)),
                ('about', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('featured_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_catalog.UserList')),
                ('widget_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widgets.WidgetList')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubfieldList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog.UserList')),
                ('subfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='field_channels.Subfield')),
            ],
            options={
                'unique_together': {('subfield', 'list')},
            },
        ),
        migrations.CreateModel(
            name='FieldSubfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfields', to='field_channels.FieldChannel')),
                ('subfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_channels.Subfield')),
            ],
            options={
                'unique_together': {('field', 'subfield')},
            },
        ),
    ]
