# Generated by Django 2.2.10 on 2020-07-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedEmailRegex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.CharField(
                        help_text="\n@spam.com: blocks all emails containing `@spam.com` like `joe@spam.com.edu`<br/>\n@spam.com$: blocks all emails ending in `@spam.com` like `joe@spam.com`<br/>\nspam.com: blocks all emails containing `spam.com` like `joe@antispam.com.edu`<br/>\nsue@gmail.com: blocks `sue@gmail.com` and `bobbysue@gmail.com`<br/>\n^sue@gmail.com: blocks `sue@gmail.com` but not `bobbysue@gmail.com`\n",
                        max_length=256,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
