# Generated by Django 2.2.10 on 2020-03-13 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoiraList",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=250, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="moira_lists", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
