# Generated by Django 4.1.9 on 2023-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_remove_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetinstance",
            name="configuration",
            field=models.JSONField(),
        ),
    ]
