FROM mitodl/mit_open_web_travis_next

WORKDIR /tmp

USER root

COPY requirements.txt /tmp/requirements.txt
COPY test_requirements.txt /tmp/test_requirements.txt
RUN pip install -r requirements.txt && pip install -r test_requirements.txt

# mit_open_web_travis comes with a copy of the source which may not match the current copy, so we need to copy it again
RUN rm -rf /src
RUN mkdir /src

WORKDIR /src

COPY . /src

RUN chown -R mitodl:mitodl /src

USER mitodl
