# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0003_channels_comments_posts")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="membership_is_managed",
            field=models.BooleanField(default=False),
        )
    ]
