# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_membership_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
