# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_membership_default_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('thumbnail', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
