# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0006_link_meta")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
