# Generated by Django 2.1.2 on 2018-11-08 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0009_alter_user_last_name_max_length"),
        ("channels", "0010_avatar_small_medium"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelGroupRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("moderators", "moderators"),
                            ("contributors", "contributors"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.Channel",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.Group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.Channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="channelsubscription", unique_together={("user", "channel")}
        ),
        migrations.AlterIndexTogether(
            name="channelsubscription", index_together={("user", "channel")}
        ),
        migrations.AlterUniqueTogether(
            name="channelgrouprole", unique_together={("channel", "group", "role")}
        ),
        migrations.AlterIndexTogether(
            name="channelgrouprole", index_together={("channel", "role")}
        ),
    ]
