# Generated by Django 2.1.2 on 2018-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0011_channel_subscriptions_roles")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
