# Generated by Django 2.1.2 on 2018-12-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
        ("channels", "0012_add_post_type_and_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="widget_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="widgets.WidgetList",
            ),
        )
    ]
