# Generated by Django 2.1.2 on 2018-12-11 18:37

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("channels", "0013_add_channel_widgetlist")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="allowed_post_types",
            field=bitfield.models.BitField(
                [("link", "link"), ("self", "self"), ("article", "article")],
                default=None,
                null=True,
            ),
        )
    ]
