# Generated by Django 2.1.2 on 2019-01-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0015_add_article_cover_image")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("restricted", "Restricted"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="title",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
