# Generated by Django 2.1.2 on 2019-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0016_add_channel_fields")]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="title",
            field=models.CharField(max_length=100, null=True),
        )
    ]
