# Generated by Django 2.1.5 on 2019-01-29 16:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("channels", "0018_add_post_and_comment_fields")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="about",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
