# Generated by Django 2.1.11 on 2019-08-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("channels", "0022_add_channel_invitation")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
