# Generated by Django 2.2.10 on 2020-03-11 21:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0023_add_subscriptions_related_name")]

    operations = [
        migrations.CreateModel(
            name="ChannelMembershipConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("query", django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ("channels", models.ManyToManyField(to="channels.Channel")),
            ],
            options={"abstract": False},
        )
    ]
