# Generated by Django 2.2.10 on 2020-03-13 15:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0024_add_channel_membership_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembershipconfig',
            name='channels',
            field=models.ManyToManyField(related_name='channel_membership_configs', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='channelmembershipconfig',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='MoiraList',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('channels', models.ManyToManyField(related_name='moira_lists', to='channels.Channel')),
                ('users', models.ManyToManyField(related_name='moira_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
