# Generated by Django 2.2.13 on 2020-07-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("channels", "0024_channel_membership_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("user_ip", models.CharField(blank=True, max_length=256, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("checks", models.IntegerField(default=1)),
                ("is_spam", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("post", "comment")},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id")},
                "index_together": {("content_type", "object_id")},
            },
        )
    ]
