# Generated by Django 2.2.13 on 2020-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0025_spamcheckresult")]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="moderator_notifications",
            field=models.BooleanField(default=False),
        )
    ]
