# Generated by Django 2.2.20 on 2021-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0026_channel_moderator_notifications")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="exclude_from_frontpage_emails",
            field=models.BooleanField(null=True),
        )
    ]
