# Generated by Django 2.2.27 on 2022-06-09 20:36

from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [("channels", "0027_post_exclude_from_frontpage_emails")]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="avatar_medium",
            field=models.ImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.avatar_uri_medium,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="avatar_small",
            field=models.ImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.avatar_uri_small,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.banner_uri,
            ),
        ),
    ]
