# Generated by Django 4.1.9 on 2023-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0028_blankable_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="channel",
            name="about",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channelmembershipconfig",
            name="query",
            field=models.JSONField(default=dict),
        ),
    ]
