# Generated by Django 4.2.25 on 2025-12-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0029_alter_article_content_alter_channel_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="archived_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this channel was archived from Reddit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="reddit_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original Reddit subreddit ID (base36)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="archived_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this comment was archived from Reddit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_reddit_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Parent comment's Reddit ID (base36)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="reddit_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original Reddit comment ID (base36)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="archived_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this post was archived from Reddit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="cached_plain_text",
            field=models.TextField(
                blank=True,
                help_text="Cached plain text version for search/display",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="reddit_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original Reddit post ID (base36)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="CommentTreeNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Denormalized score for sorting"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        help_text="Denormalized created timestamp for sorting",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Comment this node represents (null for root)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_node",
                        to="channels.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post this tree belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_nodes",
                        to="channels.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Tree Node",
                "verbose_name_plural": "Comment Tree Nodes",
                "indexes": [
                    models.Index(fields=["post", "path"], name="tree_post_path_idx"),
                    models.Index(fields=["post", "depth"], name="tree_post_depth_idx"),
                ],
            },
        ),
    ]
