title: Open Discussions
description: This provides a discussion forum for use with other MIT applications.

show_downloads: false
google_analytics:

remote_theme: pmarsceill/just-the-docs
markdown: kramdown
plugins:
  - jekyll-feed
