# Generated by Django 2.2.13 on 2020-11-12 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_add_comment_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("frontpage", "Frontpage"),
                    ("comments", "Comments"),
                    ("moderator_posts", "Moderator"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("frontpage", "Frontpage"),
                    ("comments", "Comments"),
                    ("moderator_posts", "Moderator"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PostEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("post_id", models.CharField(max_length=10)),
                (
                    "email_notification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.EmailNotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "post_id")}},
        ),
    ]
