name: Production Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [release]
  workflow_dispatch: # manual trigger

jobs:
  # runs if CI workflow was successful OR if this was manually triggered
  on-success:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "odl-open-discussions"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: release
  # runs ONLY on a failure of the CI workflow
  on-failure:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - run: echo 'The triggering workflow failed'
